// boilerplate/spa/src/vuejs/sections/home/home.vue
<template>
  <section class="s-home">
    home
  </section>
</template>
<script>

  import events from 'core/events';

  export default {

    mounted() {

      console.log('home section loaded');
      events.notifyObservers('section:loaded');
    },
    destroyed() {

      events.notifyObservers('section:destroyed');
    }
  };

</script>

// boilerplate/spa/src/sections/home/home.jsx
import events from 'core/events';
import React from 'react';

class HomeSection extends React.Component
{
  constructor(props)
  {
    super(props);
    this.name = 'HomeSection';
  }
  componentDidMount()
  {
    events.notifyObservers('section:loaded', this);
  }
  componentWillUnmount()
  {
    events.notifyObservers('section:destroyed', this);
  }
  getName()
  {
    return this.name;
  }
  render()
  {
    return (
      <section className="s-home">
        <h1>Home section</h1>
      </section>
    );
  }
}

export default HomeSection;
